# Site settings
title: Jack C
description: 'My Personal Website'
url: 'https://chaker.xyz'
baseurl: ''
profilepic: 'https://www.gravatar.com/avatar/a928b7f8c4c49402acae9b7a2497b2c3'
bkimage: '/images/bk1.jpg'
# google_analytics: UA-XXXXXX-X
font_awesome: 'fontawesome.js'

author:
  name: 'Jack C'
  email: jack@chaker.xyz
  twitter_username: jacanyyy
  github_username:  jacany

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
remote_theme: tzuehlke/jekyll-uno-timeline
